name: "Build Integration Test"
description: "Build a specified integration test project ready for running"

inputs:

  platform:
    description: "The target platform (Windows/iOS)"
    required: true

  integration_test_dir:
    description: "The integration test folder (Desktop/IOS_VisionOS/Android)"
    required: true

  build_type:
    description: "CMake build type (Release/Debug)"
    required: true

  output_folder:
    description: "Conan output folder"
    required: false
    default: "build"

  install_prefix:
    description: "Install prefix for the test-build-system"
    required: false
    default: "install"

  conan_profile_host:
    description: "Optional Conan host profile"
    required: false
    default: ""

runs:
  using: "composite"

  steps:
    - name: Conan install
      shell: bash
      run: |
        set -eux

        PROFILE="${{ inputs.conan_profile_host }}"

        PROFILE_ARG=""
        if [ -n "$PROFILE" ]; then
          PROFILE_ARG="--profile:host=$PROFILE"
        fi

        cd "${{ github.workspace }}/IntegrationTests/${{ inputs.integration_test_dir }}/"
        conan install . \
        -of "build/${{ inputs.platform }}/${{ inputs.build_type }}" \
        -s build_type=${{ inputs.build_type }} \
        -s compiler.cppstd=17 \
        -c tools.cmake.cmaketoolchain:generator=Ninja \
        --build=missing \
        $PROFILE_ARG

    - name: Configure CMake for Integration Tests
      shell: bash
      # Configure CMake using the above build directory and toolchain file generated by Conan
      run: |
        set -eux
        BUILD_TYPE_LOWER=$(echo "${{ inputs.build_type }}" | tr '[:upper:]' '[:lower:]')
        cd "${{ github.workspace }}/IntegrationTests/${{ inputs.integration_test_dir }}/"
        cmake --preset "conan-$BUILD_TYPE_LOWER" -DCMAKE_PREFIX_PATH="${{ github.workspace }}/${{ inputs.install_prefix }}"

    - name: Build Integration Tests
      shell: bash
      run: |
        BUILD_TYPE_LOWER=$(echo "${{ inputs.build_type }}" | tr '[:upper:]' '[:lower:]')
        cd "${{ github.workspace }}/IntegrationTests/${{ inputs.integration_test_dir }}/"
        cmake --build --preset conan-$BUILD_TYPE_LOWER