# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Build and test all supported platforms

# Our event to trigger this workflow
on:
  pull_request:
    branches: [ "master", "ga-test" ]

# Build all supported platforms
jobs:
  desktop:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false
      
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        build_type: [Release]

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

        # Lowercase build type once (Release -> release, Debug -> debug)
        bt_lower=$(echo "${{ matrix.build_type }}" | tr '[:upper:]' '[:lower:]')
        echo "build-type-lower=$bt_lower" >> "$GITHUB_OUTPUT"

    - name: Set up MSVC (Windows only)
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Conan
      uses: conan-io/setup-conan@v1

    - name: Install Dependencies
      shell: bash
      # Use conan to install dependencies and tooling for the build type
      run: >
        build_type_lower=$(echo "${BUILD_TYPE}" | tr '[:upper:]' '[:lower:]')
        conan install . -of build -s build_type=${{ matrix.build_type }} --build=missing -s compiler.cppstd=17 -c tools.cmake.cmaketoolchain:generator=Ninja
    
    - name: Configure CMake
      shell: bash
      # Configure CMake using the above build directory and toolchain file generated by Conan
      run: cmake --preset conan-${{ steps.strings.outputs.build-type-lower }}

    - name: Build
      shell: bash
      run: cmake --build --preset conan-${{ steps.strings.outputs.build-type-lower }}
      
    - name: Install
      shell: bash
      run: cmake --install "${{ github.workspace }}/build/build/${{ matrix.build_type }}" --config ${{ matrix.build_type }} --prefix "${{ github.workspace }}/install"

    # Integration Tests ------------------------------------

    - name: Configure CMake for Integration Tests
      shell: bash
      # Configure CMake using the above build directory and toolchain file generated by Conan
      run: |
        cmake -S "${{ github.workspace }}/IntegrationTests/Desktop" \
          -B "${{ github.workspace }}/IntegrationTests/Desktop/build" \
          -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/build/build/${{ matrix.build_type }}/generators/conan_toolchain.cmake" \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DCMAKE_FIND_DEBUG_MODE=ON \
          -DCMAKE_PREFIX_PATH="${{ github.workspace }}/install"


    - name: Build Integration Tests
      shell: bash
      run: cmake --build "${{ github.workspace }}/IntegrationTests/Desktop/build" --config ${{ matrix.build_type }}

    - name: Run Integration Tests
      shell: bash
      run: ctest --test-dir "${{ github.workspace }}/IntegrationTests/Desktop/build" -C ${{ matrix.build_type }} -V

  ios-visionos:
    runs-on: macos-latest

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false
      
      matrix:
        include:
          - platform: iOS
            simulator: iPhone 17
            sdk: iphonesimulator
            profile: ios_sim_arm
            build_type: Release
          - platform: visionOS
            simulator: Apple Vision Pro
            sdk: xrsimulator
            profile: visionos_sim_arm
            build_type: Release

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

        # Lowercase build type once (Release -> release, Debug -> debug)
        bt_lower=$(echo "${{ matrix.build_type }}" | tr '[:upper:]' '[:lower:]')
        echo "build-type-lower=$bt_lower" >> "$GITHUB_OUTPUT"

    - name: Initialize Xcode
      shell: bash
      run: |
        set -eux
        xcodebuild -version
        sudo xcodebuild -runFirstLaunch

    - name: Install Conan
      uses: conan-io/setup-conan@v1

    - name: Install Dependencies
      shell: bash
      # Use conan to install dependencies and tooling for the build type
      run: >
        build_type_lower=$(echo "${BUILD_TYPE}" | tr '[:upper:]' '[:lower:]')
        conan install . -of build/${{ matrix.platform }} -s build_type=${{ matrix.build_type }} --build=missing --profile:host="${{ github.workspace }}/profiles/host/${{ matrix.profile }}"

    - name: Configure CMake
      shell: bash
      # Configure CMake using the above build directory and toolchain file generated by Conan
      run: cmake --preset conan-${{ steps.strings.outputs.build-type-lower }}

    - name: Build
      shell: bash
      run: cmake --build --preset conan-${{ steps.strings.outputs.build-type-lower }}
      
    - name: Install
      shell: bash
      run: cmake --install "${{ github.workspace }}/build/${{ matrix.platform }}/build/${{ matrix.build_type }}" --config ${{ matrix.build_type }} --prefix "${{ github.workspace }}/install/${{ matrix.platform }}"

    - name: Shutdown any simulators
      shell: bash
      run: xcrun simctl shutdown all

    - name: Boot Simulator
      shell: bash
      run: xcrun simctl boot "${{ matrix.simulator }}"

    - name: Wait for Simulator
      shell: bash
      run: xcrun simctl bootstatus booted

    # Integration Tests ------------------------------------

    - name: Install Integration Test Dependencies
      shell: bash
      run: conan install . -of IntegrationTests/IOS_VisionOS/build/${{ matrix.platform }} -s build_type=${{ matrix.build_type }} --build=missing --profile:host="${{ github.workspace }}/profiles/host/${{ matrix.profile }}"

    - name: Configure CMake for Integration Tests
      shell: bash
      # Configure CMake using the above build directory and toolchain file generated by Conan
      run: |
        cmake -S "${{ github.workspace }}/IntegrationTests/IOS_VisionOS" \
          -B "${{ github.workspace }}/IntegrationTests/IOS_VisionOS/build" \
          -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/build/${{ matrix.platform }}/build/${{ matrix.build_type }}/generators/conan_toolchain.cmake" \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DCMAKE_FIND_DEBUG_MODE=ON \
          -DCMAKE_PREFIX_PATH="${{ github.workspace }}/install/${{ matrix.platform }}"

    - name: Build Integration Tests
      shell: bash
      run: cmake --build "${{ github.workspace }}/IntegrationTests/IOS_VisionOS/build" --config ${{ matrix.build_type }}

    - name: Run Integration Tests
      shell: bash
      run: ctest --test-dir "${{ github.workspace }}/IntegrationTests/IOS_VisionOS/build" -C ${{ matrix.build_type }} -V

  android:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

        # Lowercase build type once (Release -> release, Debug -> debug)
        bt_lower=$(echo "${{ matrix.build_type }}" | tr '[:upper:]' '[:lower:]')
        echo "build-type-lower=$bt_lower" >> "$GITHUB_OUTPUT"

    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - uses: android-actions/setup-android@v3

    - name: List Android Devices
      run: avdmanager list avd

