# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Build and test all supported platforms

# Our event to trigger this workflow
on:
  pull_request:
    branches: [ "master", "ga-test" ]

# Build all supported platforms
jobs:
  desktop:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false
      
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        build_type: [Release]
        shared: ["True", "False"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up MSVC (Windows only)
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1

    - uses: ./.github/actions/build-and-install
      with:
        build_type: ${{ matrix.build_type }}
        shared: ${{ matrix.shared }}

    # Integration Tests ------------------------------------

    - uses: ./.github/actions/build-integration-test
      with:
        platform: ${{ matrix.os }}
        integration_test_dir: Desktop
        build_type: ${{ matrix.build_type }}

    - name: Run Integration Tests
      shell: bash
      run: |
        if [ "${{ runner.os }}" = "Windows" ] && [ "${{ matrix.shared }}" = "True" ]; then
          export PATH="${{ github.workspace }}/install/:$PATH"
        fi

        ctest --test-dir "${{ github.workspace }}/IntegrationTests/Desktop/build/build/${{ matrix.build_type }}" -C ${{ matrix.build_type }} -V

  ios-visionos:
    runs-on: macos-latest

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false
      
      matrix:
        include:
          - platform: iOS
            simulator: iPhone 17
            sdk: iphonesimulator
            profile: ios_sim_arm
            build_type: Release
            shared: "False"
          - platform: visionOS
            simulator: Apple Vision Pro
            sdk: xrsimulator
            profile: visionos_sim_arm
            build_type: Release
            shared: "False"

    steps:
    - uses: actions/checkout@v4

    - name: Initialize Xcode
      shell: bash
      run: |
        set -eux
        xcodebuild -version
        sudo xcodebuild -runFirstLaunch

    - uses: ./.github/actions/build-and-install
      with:
        build_type: ${{ matrix.build_type }}
        shared: ${{ matrix.shared }}
        conan_profile_host: ${{ github.workspace }}/profiles/host/${{ matrix.profile }}

    # Integration Tests ------------------------------------

    - name: Boot Simulator
      shell: bash
      run: xcrun simctl boot "${{ matrix.simulator }}"

    - name: Wait for Simulator
      shell: bash
      run: xcrun simctl bootstatus booted

    - uses: ./.github/actions/build-integration-test
      with:
        platform: ${{ matrix.platform }}
        integration_test_dir: IOS_VisionOS
        build_type: ${{ matrix.build_type }}
        conan_profile_host: ${{ github.workspace }}/profiles/host/${{ matrix.profile }}

    - name: Run Integration Tests
      shell: bash
      run: ctest --test-dir "${{ github.workspace }}/IntegrationTests/IOS_VisionOS/build/build/${{ matrix.build_type }}" -C ${{ matrix.build_type }} -V

    - name: Shutdown simulator
      shell: bash
      run: xcrun simctl shutdown all

  android:
    runs-on: ubuntu-latest

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false
      
      matrix:
        include:
          - platform: Android
            profile: android_x86_64
            build_type: Release
            shared: "False"

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/build-and-install
      with:
        build_type: ${{ matrix.build_type }}
        shared: ${{ matrix.shared }}
        conan_profile_host: ${{ github.workspace }}/profiles/host/${{ matrix.profile }}

    # Integration Tests ------------------------------------
    - uses: ./.github/actions/build-integration-test
      with:
        platform: ${{ matrix.platform }}
        integration_test_dir: Android
        build_type: ${{ matrix.build_type }}
        conan_profile_host: ${{ github.workspace }}/profiles/host/${{ matrix.profile }}

    - uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 27
        target: default
        arch: x86_64
        # common stability options
        emulator-options: -no-window -no-audio -no-boot-anim -gpu swiftshader_indirect
        disable-animations: true
        script: |
          adb shell getprop sys.boot_completed
          ctest --test-dir "${{ github.workspace }}/IntegrationTests/Android/build/build/${{ matrix.build_type }}" -C ${{ matrix.build_type }} -V
