# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Build and test all supported platforms

# Our event to trigger this workflow
on:
  pull_request:
    branches: [ "master", "ga-test" ]

# Build all supported platforms
jobs:
  desktop:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false
      
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        build_type: [Release]

    steps:
    - uses: actions/checkout@v4

    - name: Set up MSVC (Windows only)
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1

    - uses: ./.github/actions/build-and-install
      with:
        build_type: ${{ matrix.build_type }}

    # Integration Tests ------------------------------------

    - name: Install Integration Test Dependencies
      shell: bash
      run: |
        set -eux
        cd "${{ github.workspace }}/IntegrationTests/Desktop/"
        conan install . \
        -of "IntegrationTests/Desktop/build/" \
        -s build_type=${{ matrix.build_type }} \
        -s compiler.cppstd=17 \
        -c tools.cmake.cmaketoolchain:generator=Ninja \
        --build=missing \

    - name: Configure CMake for Integration Tests
      shell: bash
      # Configure CMake using the above build directory and toolchain file generated by Conan
      run: |
        set -eux
        BUILD_TYPE_LOWER=$(echo "${{ matrix.build_type }}" | tr '[:upper:]' '[:lower:]')
        cd "${{ github.workspace }}/IntegrationTests/Desktop/"
        cmake --preset "conan-$BUILD_TYPE_LOWER" -DCMAKE_PREFIX_PATH="${{ github.workspace }}/install"

    - name: Build Integration Tests
      shell: bash
      run: |
        BUILD_TYPE_LOWER=$(echo "${{ matrix.build_type }}" | tr '[:upper:]' '[:lower:]')
        cd "${{ github.workspace }}/IntegrationTests/Desktop/"
        cmake --build --preset conan-$BUILD_TYPE_LOWER

    - name: Run Integration Tests
      shell: bash
      run: ctest --test-dir "${{ github.workspace }}/IntegrationTests/Desktop/build" -C ${{ matrix.build_type }} -V

  ios-visionos:
    runs-on: macos-latest

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false
      
      matrix:
        include:
          - platform: iOS
            simulator: iPhone 17
            sdk: iphonesimulator
            profile: ios_sim_arm
            build_type: Release
          - platform: visionOS
            simulator: Apple Vision Pro
            sdk: xrsimulator
            profile: visionos_sim_arm
            build_type: Release

    steps:
    - uses: actions/checkout@v4

    - name: Initialize Xcode
      shell: bash
      run: |
        set -eux
        xcodebuild -version
        sudo xcodebuild -runFirstLaunch

    - uses: ./.github/actions/build-and-install
      with:
        build_type: ${{ matrix.build_type }}
        conan_profile_host: ${{ github.workspace }}/profiles/host/${{ matrix.profile }}

    # Integration Tests ------------------------------------

    - name: Boot Simulator
      shell: bash
      run: xcrun simctl boot "${{ matrix.simulator }}"

    - name: Wait for Simulator
      shell: bash
      run: xcrun simctl bootstatus booted

    - name: Install Integration Test Dependencies
      shell: bash
      run: |
        set -eux
        conan install . \
        -of "IntegrationTests/IOS_VisionOS/build/${{ matrix.platform }}" \
        -s build_type=${{ matrix.build_type }} \
        -c tools.cmake.cmaketoolchain:generator=Ninja \
        --build=missing \
        --profile:host="${{ github.workspace }}/profiles/host/${{ matrix.profile }}"

    - name: Configure CMake for Integration Tests
      shell: bash
      # Configure CMake using the above build directory and toolchain file generated by Conan
      run: |
        cmake -S "${{ github.workspace }}/IntegrationTests/IOS_VisionOS" \
          -B "${{ github.workspace }}/IntegrationTests/IOS_VisionOS/build" \
          -G Ninja \
          -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/build/build/${{ matrix.platform }}/${{ matrix.build_type }}/generators/conan_toolchain.cmake" \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DCMAKE_FIND_DEBUG_MODE=ON \
          -DCMAKE_PREFIX_PATH="${{ github.workspace }}/install/${{ matrix.platform }}"

    - name: Build Integration Tests
      shell: bash
      run: cmake --build "${{ github.workspace }}/IntegrationTests/IOS_VisionOS/build" --config ${{ matrix.build_type }}

    - name: Run Integration Tests
      shell: bash
      run: ctest --test-dir "${{ github.workspace }}/IntegrationTests/IOS_VisionOS/build" -C ${{ matrix.build_type }} -V

    - name: Shutdown simulator
      shell: bash
      run: xcrun simctl shutdown all

  android:
    runs-on: ubuntu-latest

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false
      
      matrix:
        include:
          - platform: Android
            profile: android_x86_64
            build_type: Release

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/build-and-install
      with:
        build_type: ${{ matrix.build_type }}
        conan_profile_host: ${{ github.workspace }}/profiles/host/${{ matrix.profile }}

    # Integration Tests ------------------------------------
    - name: Install Integration Test Dependencies
      shell: bash
      run: |
        set -eux
        conan install . \
        -of "IntegrationTests/Android/build/${{ matrix.platform }}" \
        -s build_type=${{ matrix.build_type }} \
        -s compiler.cppstd=17 \
        -c tools.cmake.cmaketoolchain:generator=Ninja \
        --build=missing \
        --profile:host="${{ github.workspace }}/profiles/host/${{ matrix.profile }}"

    - name: Configure CMake for Integration Tests
      shell: bash
      # Configure CMake using the above build directory and toolchain file generated by Conan
      run: |
        cmake -S "${{ github.workspace }}/IntegrationTests/Android" \
          -B "${{ github.workspace }}/IntegrationTests/Android/build" \
          -G Ninja \
          -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/build/build/${{ matrix.platform }}/${{ matrix.build_type }}/generators/conan_toolchain.cmake" \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DCMAKE_FIND_DEBUG_MODE=ON \
          -DCMAKE_PREFIX_PATH="${{ github.workspace }}/install/${{ matrix.platform }}"

    - name: Build Integration Tests
      shell: bash
      run: cmake --build "${{ github.workspace }}/IntegrationTests/Android/build" --config ${{ matrix.build_type }}

    - uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 27
        target: default
        arch: x86_64
        # common stability options
        emulator-options: -no-window -no-audio -no-boot-anim -gpu swiftshader_indirect
        disable-animations: true
        script: |
          adb shell getprop sys.boot_completed
          ctest --test-dir "${{ github.workspace }}/IntegrationTests/Android/build" -C ${{ matrix.build_type }} -V
